MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/users')

  resources :users, only: [:index, :show, :new, :create]

  resources :bands

  resources :albums, except: [:index]

  resources :tracks

  resource :session, only: [:new, :create, :destroy]


end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :string           not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord

  validates :band_id, :title, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :title, uniqueness: true

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id

  has_many :tracks, dependent: :destroy

end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id

  has_many :tracks,
    through: :albums,
    source: :tracks

end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  album_id   :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  bonus      :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :email, :password_digest, :session_token, presence: true, uniqueness: true
  # validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!

    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:success] = "Album successfully created!"
      redirect_to band_url(@album.band)
    else
      flash[:errors] = "Couldn't create a album ｡･ﾟ･(ﾉД`)ヽ(￣ω￣ )"
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      flash[:success] = "Successfully edited album!"
      redirect_to album_url(@album)
    else
      flash[:errors] = @albums.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:success] = "Byebye :("
    redirect_to albums_url
  end

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live)
  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def require_user!
    unless logged_in?
      flash[:errors] = "Sorry, u gotta log in to access this :333"
      redirect_to new_session_url
    end
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      flash[:success] = "Band successfully created!"
      redirect_to bands_url
    else
      flash[:errors] = "Couldn't create a band ｡･ﾟ･(ﾉД`)ヽ(￣ω￣ )"
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    @albums = @band.albums
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      flash[:success] = "Successfully edited band!"
      redirect_to band_url(@band)
    else
      flash[:errors] = @bands.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    flash[:success] = "Byebye :("
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name)
  end

end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      log_in_user!(user)
      flash[:success] = "Successfully logged in!"
      redirect_to root_url
    else
      flash[:errors] = "Bad auth credentials"
      redirect_to new_session_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      flash[:success] = "Track successfully created!"
      redirect_to album_url(@track.album)
    else
      flash[:errors] = "Couldn't create a track ｡･ﾟ･(ﾉД`)ヽ(￣ω￣ )"
      render :new
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      flash[:success] = "Successfully edited track!"
      redirect_to bands_url
    else
      flash[:errors] = @tracks.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    flash[:success] = "Byebye :("
    redirect_to tracks_url
  end

  def track_params
    params.require(:track).permit(:title, :album_id, :ord, :lyrics, :bonus)
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      flash[:success] = "Successfully signed up!"
      email = UserMailer.welcome_email(@user)
      email.deliver
      redirect_to user_url(@user)
    else
      flash[:error] = "Bad auth credentials"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/albums/edit.html.erb
<!-- create an album page -->

<h1>CHANG IT UP!</h1>

<form action="<%= album_url(@album) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>What's your album's title?:
    <input type="text" name="album[title]" value="<%= @album.title %>" />
  </label>
  <br>

  <label>What year was it ~released?~:
    <input type="text" name="album[year]" value="<%= @album.year %>" />
  </label>
  <br>

  <label>Is it a live album? Or studio?
  <input type="radio" name="album[live]" value="true">Laive!</input>
  <input type="radio" name="album[live]" value="false">Stoodio</input>
  </label>
  <br>

  <label for="band">Which band made that album?
  <select id="band" name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
    <% end %>
  </select>
  <br>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/albums/new.html.erb
<!-- create a album page -->

<h1>Register your album!</h1>

<form action="<%= albums_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>What's your album's title?:
    <input type="text" name="album[title]" value="" />
  </label>
  <br>

  <label>What year was it ~released?~:
    <input type="text" name="album[year]" value="" />
  </label>
  <br>

  <label>Is it a live album? Or studio?
  <input type="radio" name="album[live]" value="true">Laive!</input>
  <input type="radio" name="album[live]" value="false">Stoodio</input>
  </label>
  <br>

  <label for="band">Which band made that album?
  <select id="band" name="album[band_id]">
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
    <% end %>
  </select>
  <br>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/albums/show.html.erb
<br>Your albums's name is: <%= @album.title %>
<br><br>

<h2>Tracks:</h2>


<ul>
  <% @album.tracks.each do |track| %>
    <% if track.bonus == true %>
      <% bonus_status = "Bonus Track" %>
    <% elsif track.bonus == false %>
      <% bonus_status = "Regular Track" %>
    <% end %>
    <li>Title: <%= track.title %></li>
    <li>Album: <%= track.album.title %></li>
    <li>Track Number: <%= track.ord %></li>
    <li>Bonus?: <%= bonus_status %></li>
    <li>Lyrics: <%= track.lyrics %></li>
  <% end %>
</ul>

<br><br>
<%= link_to 'WANNA ADD SOME TRAXX?!?! click hurr', new_track_url %>

MusicApp/app/views/bands/edit.html.erb
<!-- edit a band page -->

<h1>Can't believe you literally wrote your band's name wrong but here:</h1>

<form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>Once again... what's your band's name?:
    <input type="text" name="band[name]" value="<%= @band.name %>" />
  </label>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/bands/index.html.erb
<h2>Here's the hottest new bands:</h2>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
    <li><a href="<%= edit_band_url(band) %>"><p>Edit ur band~ name!</p></a></li>
    <li>
      <form action="<%= band_url(band) %>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE" />
        <input type="submit" value="Delete ur band :'(" />
      </form></li>
    <br><br>
  <% end %>
</ul>

MusicApp/app/views/bands/new.html.erb
<!-- create a band page -->

<h1>Register your band!</h1>

<form action="<%= bands_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>What's your band's name?:
    <input type="text" name="band[name]" value="" />
  </label>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/bands/show.html.erb
<br>Your band's name is: <%= @band.name %><br>
<h2>Here's your band's albums...</h2>

<ul>
  <% @albums.each do |album| %>
    <li><%= link_to "#{album.title}", album_url(album) %></li>
  <% end %>
</ul>

<br>

<%= link_to 'Load your fav album!!', new_album_url %>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="flex-container"">
      <marquee behavior=scroll direction="left" scrollamount="30"><header class="title">
        ♫♪♩MUSIC APP!♩♪♫
      </header></marquee>


      <nav>
        <%= link_to "Take me home", users_url %>
        <section class="log_in">
      <% if logged_in? %>
          <p>
            Currently logged in as <%= current_user.email %>&nbsp;&nbsp;&nbsp;<form action="<%= session_url %>" method="POST">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="_method" value="DELETE">
              <input type="submit" value="Log out!" />
            </form>
          </p>
        </section>
      </nav>
        <section class= "bands">
          <%= link_to 'Create a band!', new_band_url %>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'View all bands', bands_url %>
        </section>
      <% else %>
        <%= link_to "Log in already! :3", new_session_url %>
        <%= link_to "Or.. maybe register??", new_user_url %>
      </nav>
      <% end %>
      <br><br>

      <% if flash[:errors] or flash[:success] %>
        <%= flash[:errors] %>
        <%= flash[:success] %>
        <br><br>
      <% end %>



      <%= yield %>
    </div>
  </body>
</html>

MusicApp/app/views/tracks/edit.html.erb
<!-- create an album page -->

<h1>CHANG IT UP!</h1>

<form action="<%= album_url(@album) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>What's your album's title?:
    <input type="text" name="album[title]" value="<%= @album.title %>" />
  </label>
  <br>

  <label>What year was it ~released?~:
    <input type="text" name="album[year]" value="<%= @album.year %>" />
  </label>
  <br>

  <label>Is it a live album? Or studio?
  <input type="radio" name="album[live]" value="true">Laive!</input>
  <input type="radio" name="album[live]" value="false">Stoodio</input>
  </label>
  <br>

  <label for="track">Which band made that album?
  <select id="track" name="album[band_id]">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"><%= album.title %></option>
    <% end %>
  </select>
  <br>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/tracks/new.html.erb
<!-- create a album page -->

<h1>Register your track!</h1>

<form action="<%= tracks_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>What's your tracks's title?:
    <input type="text" name="track[title]" value="" />
  </label>
  <br>

  <label>What's the track numer?:
    <input type="text" name="track[ord]" value="" />
  </label>
  <br>

  <label>Is it a bonus track? Or just regular?
    <input type="radio" name="track[bonus]" value="true">Bonoos!</input>
    <input type="radio" name="track[bonus]" value="false">Regs :'[</input>
  </label>
  <br>

  <label for="album">Which album is this on again?
  <select id="album" name="track[album_id]">
    <% Album.all.each do |album| %>
      <option value="<%= album.id %>"><%= album.title %></option>
    <% end %>
  </select>
  <br>

  <label>Lyrics?? <3
    <textarea name="track[lyrics]">Enter some lyrics if you'd like!</textarea>
  </label>

  <input type="submit" value="Hit it!" />
</form>

MusicApp/app/views/tracks/show.html.erb
<br>Your albums's name is: <%= @album.title %>

MusicApp/app/views/users/index.html.erb
<h2>Make some friends!!!!</h2>

<ul>
  <% @users.each do |user| %>
    <li><a href="<%= user_url(user) %>"><p><%= user.email %></p></a></li>
    <br><br>
  <% end %>
</ul>

MusicApp/app/views/users/new.html.erb
<!-- sign up page -->

<h1>Create a new account!</h1>

<%= link_to 'Sign in!', new_session_url %>

<form action="<%= users_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Email
    <input type="text" name="user[email]" value="" />
  </label>

  <label>Password
    <input type="password" name="user[password]" value="" />
  </label>

  <input type="submit" value="Create an account!" />
</form>

MusicApp/app/views/users/show.html.erb
This user's email is <%= @user.email %>. Idk email them or something!